# Generated by Django 4.2.3 on 2023-08-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SCHname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panda', to='app.school'),
        ),
    ]
